#pragma once

typedef enum {
  KeyModCtrlL           = 0x01u,
  KeyModShiftL          = 0x02u,
  KeyModAltL            = 0x04u,
  KeyModMetaL           = 0x08u,
  KeyModCtrlR           = 0x10u,
  KeyModShiftR          = 0x20u,
  KeyModAltR            = 0x40u,
  KeyModMetaR           = 0x80u,
  KeyNone               = 0x00u, // No key pressed
  KeyErrOvf             = 0x01u, // Keyboard Error Roll Over
  KeyA                  = 0x04u, // Keyboard a and A
  KeyB                  = 0x05u, // Keyboard b and B
  KeyC                  = 0x06u, // Keyboard c and C
  KeyD                  = 0x07u, // Keyboard d and D
  KeyE                  = 0x08u, // Keyboard e and E
  KeyF                  = 0x09u, // Keyboard f and F
  KeyG                  = 0x0au, // Keyboard g and G
  KeyH                  = 0x0bu, // Keyboard h and H
  KeyI                  = 0x0cu, // Keyboard i and I
  KeyJ                  = 0x0du, // Keyboard j and J
  KeyK                  = 0x0eu, // Keyboard k and K
  KeyL                  = 0x0fu, // Keyboard l and L
  KeyM                  = 0x10u, // Keyboard m and M
  KeyN                  = 0x11u, // Keyboard n and N
  KeyO                  = 0x12u, // Keyboard o and O
  KeyP                  = 0x13u, // Keyboard p and P
  KeyQ                  = 0x14u, // Keyboard q and Q
  KeyR                  = 0x15u, // Keyboard r and R
  KeyS                  = 0x16u, // Keyboard s and S
  KeyT                  = 0x17u, // Keyboard t and T
  KeyU                  = 0x18u, // Keyboard u and U
  KeyV                  = 0x19u, // Keyboard v and V
  KeyW                  = 0x1au, // Keyboard w and W
  KeyX                  = 0x1bu, // Keyboard x and X
  KeyY                  = 0x1cu, // Keyboard y and Y
  KeyZ                  = 0x1du, // Keyboard z and Z
  Key1                  = 0x1eu, // Keyboard 1 and !
  Key2                  = 0x1fu, // Keyboard 2 and @
  Key3                  = 0x20u, // Keyboard 3 and #
  Key4                  = 0x21u, // Keyboard 4 and $
  Key5                  = 0x22u, // Keyboard 5 and %
  Key6                  = 0x23u, // Keyboard 6 and ^
  Key7                  = 0x24u, // Keyboard 7 and &
  Key8                  = 0x25u, // Keyboard 8 and *
  Key9                  = 0x26u, // Keyboard 9 and (
  Key0                  = 0x27u, // Keyboard 0 and )
  KeyEnter              = 0x28u, // Keyboard Return (ENTER)
  KeyEsc                = 0x29u, // Keyboard ESCAPE
  KeyBackspace          = 0x2au, // Keyboard DELETE (Backspace)
  KeyTab                = 0x2bu, // Keyboard Tab
  KeySpace              = 0x2cu, // Keyboard Spacebar
  KeyMinus              = 0x2du, // Keyboard - and _
  KeyEqual              = 0x2eu, // Keyboard = and +
  KeyLeftBrace          = 0x2fu, // Keyboard [ and {
  KeyRightBrace         = 0x30u, // Keyboard ] and }
  KeyBackslash          = 0x31u, // Keyboard \ and |
  KeyHashTilde          = 0x32u, // Keyboard Non-US # and ~
  KeySemicolon          = 0x33u, // Keyboard ; and :
  KeyApostrophe         = 0x34u, // Keyboard ' and "
  KeyGrave              = 0x35u, // Keyboard ` and ~
  KeyComma              = 0x36u, // Keyboard , and <
  KeyDot                = 0x37u, // Keyboard . and >
  KeySlash              = 0x38u, // Keyboard / and ?
  KeyCapsLock           = 0x39u, // Keyboard Caps Lock
  KeyF1                 = 0x3au, // Keyboard F1
  KeyF2                 = 0x3bu, // Keyboard F2
  KeyF3                 = 0x3cu, // Keyboard F3
  KeyF4                 = 0x3du, // Keyboard F4
  KeyF5                 = 0x3eu, // Keyboard F5
  KeyF6                 = 0x3fu, // Keyboard F6
  KeyF7                 = 0x40u, // Keyboard F7
  KeyF8                 = 0x41u, // Keyboard F8
  KeyF9                 = 0x42u, // Keyboard F9
  KeyF10                = 0x43u, // Keyboard F10
  KeyF11                = 0x44u, // Keyboard F11
  KeyF12                = 0x45u, // Keyboard F12
  KeySysrq              = 0x46u, // Keyboard Print Screen
  KeyScrollLock         = 0x47u, // Keyboard Scroll Lock
  KeyPause              = 0x48u, // Keyboard Pause
  KeyInsert             = 0x49u, // Keyboard Insert
  KeyHome               = 0x4au, // Keyboard Home
  KeyPageUp             = 0x4bu, // Keyboard Page Up
  KeyDelete             = 0x4cu, // Keyboard Delete Forward
  KeyEnd                = 0x4du, // Keyboard End
  KeyPageDown           = 0x4eu, // Keyboard Page Down
  KeyRight              = 0x4fu, // Keyboard Right Arrow
  KeyLeft               = 0x50u, // Keyboard Left Arrow
  KeyDown               = 0x51u, // Keyboard Down Arrow
  KeyUp                 = 0x52u, // Keyboard Up Arrow
  KeyNumLock            = 0x53u, // Keyboard Num Lock and Clear
  KeyKpSlash            = 0x54u, // Keypad /
  KeyKpAsterisk         = 0x55u, // Keypad *
  KeyKpMinus            = 0x56u, // Keypad -
  KeyKpPlus             = 0x57u, // Keypad +
  KeyKpEnter            = 0x58u, // Keypad ENTER
  KeyKP1                = 0x59u, // Keypad 1 and End
  KeyKP2                = 0x5au, // Keypad 2 and Down Arrow
  KeyKP3                = 0x5bu, // Keypad 3 and PageDn
  KeyKP4                = 0x5cu, // Keypad 4 and Left Arrow
  KeyKP5                = 0x5du, // Keypad 5
  KeyKP6                = 0x5eu, // Keypad 6 and Right Arrow
  KeyKP7                = 0x5fu, // Keypad 7 and Home
  KeyKP8                = 0x60u, // Keypad 8 and Up Arrow
  KeyKP9                = 0x61u, // Keypad 9 and Page Up
  KeyKP0                = 0x62u, // Keypad 0 and Insert
  KeyKpDot              = 0x63u, // Keypad . and Delete
  Key102ND              = 0x64u, // Keyboard Non-US \ and |
  KeyCompose            = 0x65u, // Keyboard Application
  KeyPower              = 0x66u, // Keyboard Power
  KeyKpequal            = 0x67u, // Keypad =
  KeyF13                = 0x68u, // Keyboard F13
  KeyF14                = 0x69u, // Keyboard F14
  KeyF15                = 0x6au, // Keyboard F15
  KeyF16                = 0x6bu, // Keyboard F16
  KeyF17                = 0x6cu, // Keyboard F17
  KeyF18                = 0x6du, // Keyboard F18
  KeyF19                = 0x6eu, // Keyboard F19
  KeyF20                = 0x6fu, // Keyboard F20
  KeyF21                = 0x70u, // Keyboard F21
  KeyF22                = 0x71u, // Keyboard F22
  KeyF23                = 0x72u, // Keyboard F23
  KeyF24                = 0x73u, // Keyboard F24
  KeyOpen               = 0x74u, // Keyboard Execute
  KeyHelp               = 0x75u, // Keyboard Help
  KeyProps              = 0x76u, // Keyboard Menu
  KeyFront              = 0x77u, // Keyboard Select
  KeyStop               = 0x78u, // Keyboard Stop
  KeyAgain              = 0x79u, // Keyboard Again
  KeyUndo               = 0x7au, // Keyboard Undo
  KeyCut                = 0x7bu, // Keyboard Cut
  KeyCopy               = 0x7cu, // Keyboard Copy
  KeyPaste              = 0x7du, // Keyboard Paste
  KeyFind               = 0x7eu, // Keyboard Find
  KeyMute               = 0x7fu, // Keyboard Mute
  KeyVolumeUp           = 0x80u, // Keyboard Volume Up
  KeyVolumeDown         = 0x81u, // Keyboard Volume Down
  KeyKpComma            = 0x85u, // Keypad Comma
  KeyRo                 = 0x87u, // Keyboard International1
  KeyKatakanaHiragana   = 0x88u, // Keyboard International2
  KeyYen                = 0x89u, // Keyboard International3
  KeyHenkan             = 0x8au, // Keyboard International4
  KeyMuhenkan           = 0x8bu, // Keyboard International5
  KeyKpJpComma          = 0x8cu, // Keyboard International6
  KeyHangeul            = 0x90u, // Keyboard LANG1
  KeyHanja              = 0x91u, // Keyboard LANG2
  KeyKatakana           = 0x92u, // Keyboard LANG3
  KeyHiragana           = 0x93u, // Keyboard LANG4
  KeyZenkakuhankaku     = 0x94u, // Keyboard LANG5
  KeyKpLeftParen        = 0xb6u, // Keypad (
  KeyKpRightParen       = 0xb7u, // Keypad )
  KeyLeftCtrl           = 0xe0u, // Keyboard Left Control
  KeyLeftShift          = 0xe1u, // Keyboard Left Shift
  KeyLeftAlt            = 0xe2u, // Keyboard Left Alt
  KeyLeftMeta           = 0xe3u, // Keyboard Left GUI
  KeyRightCtrl          = 0xe4u, // Keyboard Right Control
  KeyRightShift         = 0xe5u, // Keyboard Right Shift
  KeyRightAlt           = 0xe6u, // Keyboard Right Alt
  KeyRightMeta          = 0xe7u, // Keyboard Right GUI
  KeyMediaPlayPause     = 0xe8u, 
  KeyMediaStopCD        = 0xe9u,
  KeyMediaPreviousSong  = 0xeau,
  KeyMediaNextSong      = 0xebu,
  KeyMediaEjectCD       = 0xecu,
  KeyMediaVolumeUp      = 0xedu,
  KeyMediaVolumeDown    = 0xeeu,
  KeyMediaMute          = 0xefu,
  KeyMediaWww           = 0xf0u,
  KeyMediaBack          = 0xf1u,
  KeyMediaForward       = 0xf2u,
  KeyMediaStop          = 0xf3u,
  KeyMediaFind          = 0xf4u,
  KeyMediaScrollUp      = 0xf5u,
  KeyMediaScrollDown    = 0xf6u,
  KeyMediaEdit          = 0xf7u,
  KeyMediaSleep         = 0xf8u,
  KeyMediaCoffee        = 0xf9u,
  KeyMediaRefresh       = 0xfau,
  KeyMediaCalc          = 0xfbu,
  KeyCount              = 0xffu,
} Scancode;
